# -*- coding: utf-8 -*-
"""CMPT_211_Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14vYQOobe0hWgPiMQhUDapJ6WliG3ihIS
"""

print ("Concordia University of Edmonton (CUE)")
print("IT 211 A: Introduction to Software Development ")
print("Winter 2024")
print("Assignment 1")
print("Submit the Answer in ipynb file")
studentID=1001 #enter you id here
if studentID%2==0:
   print("Aaswer the even problems")
else:
   print("Answer the odd problems")

"""## Problem 1 (10 points): Contains Duplicate
Given an integer array nums, return true if any value appears at least twice in the array, and return false if every element is distinct.

Example 1:
- Input: nums = [1,2,3,1]
- Output: true

Example 2:
- Input: nums = [1,2,3,4]
- Output: false

Example 3:
- Input: nums = [1,1,1,3,3,4,3,2,4,2]
- Output: true

Constraints:
- 1 <= nums.length <= 105
- -109 <= nums[i] <= 109
"""

# Add the solution here

"""## Problem 2 (10 points): Single Number
Given a non-empty array of integers nums, every element appears twice except for one. Find that single one.

You must implement a solution with a linear runtime complexity and use only constant extra space.

Example 1:
- Input: nums = [2,2,1]
- Output: 1

Example 2:
- Input: nums = [4,1,2,1,2]
- Output: 4

Example 3:
- Input: nums = [1]
- Output: 1

Constraints:
- 1 <= nums.length <= 3 * 104
- -3 * 104 <= nums[i] <= 3 * 104

Each element in the array appears twice except for one element which appears only once.
"""

# Add the solution here

"""## Problem 3 (10 points): Valid Palindrome
A phrase is a palindrome if, after converting all uppercase letters into lowercase letters and removing all non-alphanumeric characters, it reads the same forward and backward. Alphanumeric characters include letters and numbers.

Given a string s, return true if it is a palindrome, or false otherwise.

Example 1:
- Input: s = "A man, a plan, a canal: Panama"
- Output: true
- Explanation: "amanaplanacanalpanama" is a palindrome.

Example 2:
- Input: s = "race a car"
- Output: false
- Explanation: "raceacar" is not a palindrome.

Example 3:
- Input: s = " "
- Output: true
- Explanation: s is an empty string "" after removing non-alphanumeric characters. Since an empty string reads the same forward and backward, it is a palindrome.


Constraints:
- 1 <= s.length <= 2 * 105
- s consists only of printable ASCII characters.
"""

# Add solution here

"""## Problem 4 (10 points): Plus One
You are given a large integer represented as an integer array digits, where each digits[i] is the ith digit of the integer. The digits are ordered from most significant to least significant in left-to-right order. The large integer does not contain any leading 0's.

Increment the large integer by one and return the resulting array of digits.

Example 1:
- Input: digits = [1,2,3]
- Output: [1,2,4]
- Explanation: The array represents the integer 123. Incrementing by one gives 123 + 1 = 124. Thus, the result should be [1,2,4].

Example 2:
- Input: digits = [4,3,2,1]
- Output: [4,3,2,2]
- Explanation: The array represents the integer 4321. Incrementing by one gives 4321 + 1 = 4322. Thus, the result should be [4,3,2,2].

Example 3:
- Input: digits = [9]
- Output: [1,0]
- Explanation: The array represents the integer 9.
- Incrementing by one gives 9 + 1 = 10. Thus, the result should be [1,0].


Constraints:
- 1 <= digits.length <= 100
- 0 <= digits[i] <= 9
- digits does not contain any leading 0's.
"""

# Add solution here

"""## Problem 5 (10 Points) Add Binary
Given two binary strings a and b, return their sum as a binary string.

Example 1:
- Input: a = "11", b = "1"
- Output: "100"

Example 2:
- Input: a = "1010", b = "1011"
- Output: "10101"


Constraints:
- 1 <= a.length, b.length <= 104
- a and b consist only of '0' or '1' characters.
- Each string does not contain leading zeros except for the zero itself.
"""

# Add solution here

"""## Problem 6 (10 points) Reverse String
Write a function that reverses a string. The input string is given as an array of characters s.

You must do this by modifying the input array in-place with O(1) extra memory.

Example 1:
- Input: s = ["h","e","l","l","o"]
- Output: ["o","l","l","e","h"]

Example 2:
- Input: s = ["H","a","n","n","a","h"]
- Output: ["h","a","n","n","a","H"]

Constraints:
- 1 <= s.length <= 105
- s[i] is a printable ascii character.
"""

# Add solution here

"""## Probelm 7 (10 points) Sorting the Sentence
A sentence is a list of words that are separated by a single space with no leading or trailing spaces. Each word consists of lowercase and uppercase English letters.

A sentence can be shuffled by appending the 1-indexed word position to each word then rearranging the words in the sentence.

For example, the sentence "This is a sentence" can be shuffled as "sentence4 a3 is2 This1" or "is2 sentence4 This1 a3".
Given a shuffled sentence s containing no more than 9 words, reconstruct and return the original sentence.

Example 1:
- Input: s = "is2 sentence4 This1 a3"
- Output: "This is a sentence"
- Explanation: Sort the words in s to their original positions "This1 is2 a3 sentence4", then remove the numbers.


Example 2:
- Input: s = "Myself2 Me1 I4 and3"
- Output: "Me Myself and I"
- Explanation: Sort the words in s to their original positions "Me1 Myself2 and3 I4", then remove the numbers.


Constraints:
- 2 <= s.length <= 200
- s consists of lowercase and uppercase English letters, spaces, and digits from 1 to 9.
- The number of words in s is between 1 and 9.
- The words in s are separated by a single space.
- s contains no leading or trailing spaces
"""

# Add the solution here

"""## Probelm 8 (10 points) Merge Two Sorted List
ou are given the heads of two sorted linked lists list1 and list2.

Merge the two lists into one sorted list. The list should be made by splicing together the nodes of the first two lists.

Return the head of the merged linked list.

![list](https://assets.leetcode.com/uploads/2020/10/03/merge_ex1.jpg)


Example 1:
- Input: list1 = [1,2,4], list2 = [1,3,4]
- Output: [1,1,2,3,4,4]

Example 2:
- Input: list1 = [], list2 = []
- Output: []

Example 3:
- Input: list1 = [], list2 = [0]
- Output: [0]

Constraints:
- The number of nodes in both lists is in the range [0, 50].
- -100 <= Node.val <= 100
- Both list1 and list2 are sorted in non-decreasing order.
"""

# Add the solution here

"""## Problem 9 (10 points) Binary Search
Given an array of integers nums which is sorted in ascending order, and an integer target, write a function to search target in nums. If target exists, then return its index. Otherwise, return -1.

You must write an algorithm with O(log n) runtime complexity.



Example 1:
- Input: nums = [-1,0,3,5,9,12], target = 9
- Output: 4
- Explanation: 9 exists in nums and its index is 4

Example 2:
- Input: nums = [-1,0,3,5,9,12], target = 2
- Output: -1
- Explanation: 2 does not exist in nums so return -1

Constraints:
- 1 <= nums.length <= 104
- -104 < nums[i], target < 104
- All the integers in nums are unique.
- nums is sorted in ascending order.
"""

# Add solution here

"""## Probem 10 (10 points): Search Insert Position
Given a sorted array of distinct integers and a target value, return the index if the target is found. If not, return the index where it would be if it were inserted in order.

You must write an algorithm with O(log n) runtime complexity.

Example 1:
- Input: nums = [1,3,5,6], target = 5
- Output: 2

Example 2:
- Input: nums = [1,3,5,6], target = 2
- Output: 1

Example 3:
- Input: nums = [1,3,5,6], target = 7
- Output: 4

Constraints:
- 1 <= nums.length <= 104
- -104 <= nums[i] <= 104
- nums contains distinct values sorted in ascending order.
- -104 <= target <= 104
"""

# Add solution here