# -*- coding: utf-8 -*-
"""cmpt211_week_1_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GiUtjj376v6SqepFdKXPLT5BLhFgTuD3

# CMPT 211: Weeks 1-3 Master Activity Notebook
**Winter 2026 | Instructor: Bernal Manzanilla**

This notebook consolidates the coding activities for the first three weeks of class.
* **Week 1:** Basics, Strings, and single-item cleaning.
* **Week 2:** Control Flow (Loops), Lists, and batch processing.
* **Week 3:** Functions (Structured Programming) and modularization.

---
### 🛠️ Setup: Git Simulation
Run this cell to set up a temporary Git repository in this Colab environment so we can practice our version control commands alongside the code.
"""

# Commented out IPython magic to ensure Python compatibility.
# Initialize a fake git repo for practice inside Colab
!git config --global user.email "student@concordia.ab.ca"
!git config --global user.name "Student Name"
!mkdir cmpt211_lab_work
# %cd cmpt211_lab_work
!git init
print("\n Simulation Repository Initialized")

"""##  Week 1: Data Types & Variables
**Think Python Ch 1-2**

**Task:** We received a single raw piece of data from a web scraper: `"  $12.99 "`.
Our goal is to clean it using basic string methods.

**Concepts:**
* Variables & Assignment
* Strings (str) vs Floats (float)
* String Methods (`.strip()`)
"""

# --- Week 1 Script: Clean One Item ---

raw_price = "  $12.99 "
print(f"Raw Input: '{raw_price}'")

# 1. Clean whitespace
clean_step_1 = raw_price.strip()
print(f"Step 1 (Strip): '{clean_step_1}'")

# 2. Remove the dollar sign
# String slicing: [start:end]
clean_step_2 = clean_step_1[1:]
print(f"Step 2 (Slice): '{clean_step_2}'")

# 3. Convert to number (float)
final_price = float(clean_step_2)
print(f"Step 3 (Typecast): {final_price}")
print(f"Final Type: {type(final_price)}")

# --- Save this work to a file for Git ---
# We use Python file I/O to create the script file 'lab1.py'
with open("lab1.py", "w") as f:
    f.write('raw_price = "  $12.99 "\nprint(float(raw_price.strip()[1:]))')

# --- Week 1 Git Task ---
# Commit our first script
!git add lab1.py
!git commit -m "Week 1: Completed single item cleaning script"

"""##  Week 2: Control Flow (Loops & Logic)
**Think Python Ch 7-8**

**Task:** We now have a *list* of messy data, including errors. We need to process them all automatically.

**Concepts:**
* Lists (`[]`)
* Iteration (`for` loops)
* Conditionals (`if`, `elif`, `else`)
* `continue` vs `break`
"""

# --- Week 2 Script: Batch Cleaning ---

# A list of messy data
raw_data_list = ["  $12.99 ", "15.50", "ERROR", " $9.99", "free", "  $100.00"]
clean_prices = []
total_revenue = 0.0

print("--- Starting Batch Processing ---")

for item in raw_data_list:
    # 1. Strip whitespace
    item = item.strip()

    # 2. Handle known errors (Control Flow)
    if item == "ERROR":
        print(f" error: Skipping invalid entry")
        continue # Skip to next loop iteration

    # 3. Handle 'free' items
    if item == "free":
        price = 0.0
    else:
        # 4. Handle standard prices
        if item.startswith('$'):
            item = item[1:] # Remove $
        price = float(item)

    # Add to list and sum
    clean_prices.append(price)
    total_revenue += price
    print(f"Converted: {price}")

print("-" * 30)
print(f"Final Data: {clean_prices}")
print(f"Total Revenue: ${total_revenue:.2f}")

# --- Save to file for Git ---
with open("lab2.py", "w") as f:
    f.write("# Week 2 Code would go here")

# --- Week 2 Git Task ---
# Commit the new logic script
!git add lab2.py
!git commit -m "Week 2: Added loop support and error handling"

# Check our history
!git log --oneline

"""##  Week 3: Structured Programming (Functions)
**Think Python Ch 3 & 6**

**Task:** Our code in Week 2 is messy and hard to reuse. We will refactor it into a **Function**.
This follows the **Structured Programming** paradigm: breaking a large problem into small, named steps.

**Concepts:**
* Defining Functions (`def`)
* Parameters & Arguments
* Return Values
* Docstrings
"""

# --- Week 3 Script: Modular Functions ---

def clean_currency(price_str):
    """
    Takes a raw string input, removes whitespace and currency symbols,
    and returns a float. Returns None if input is invalid.
    """
    # Defensive programming: Handle non-strings
    if not isinstance(price_str, str):
        return None

    cleaned = price_str.strip()

    # Business Logic
    if cleaned == "ERROR":
        return None
    if cleaned == "free":
        return 0.0

    if cleaned.startswith('$'):
        cleaned = cleaned[1:]

    try:
        return float(cleaned)
    except ValueError:
        return None

# --- Main Program Flow ---
print("--- Testing Function ---")
raw_data_list = ["  $12.99 ", "15.50", "ERROR", " $9.99", "free"]

for raw in raw_data_list:
    result = clean_currency(raw)

    if result is not None:
        print(f" Success: {result}")
    else:
        print(f" Failed/Skipped: '{raw}'")

# --- Save to file for Git ---
with open("lab3_functions.py", "w") as f:
    f.write("# Week 3 Code would go here")

# --- Week 3 Git Task ---
# We are moving to a new 'paradigm', so let's use a branch!
!git checkout -b feature/structured-functions
!git add lab3_functions.py
!git commit -m "Week 3: Refactored logic into clean_currency function"

# Visualizing the branch
!git log --oneline --graph --all